package com.eastwest.dto.license;

public enum LicenseEntitlement {
    SSO,
    WORK_ORDER_HISTORY,
    WORKFLOW,
    MULTI_INSTANCE,
    WEBHOOK,//TODO
    BRANDING,
    NFC_BARCODE,
    CUSTOM_ROLES,
    FILE_ATTACHMENTS,
    TIME_TRACKING,
    COST_TRACKING,
    WORK_ORDER_LINKING,
    SIGNATURE_CAPTURE,
    PM_CALENDAR,
    CONDITION_BASED_PM,//meter triggered PM
    ASSET_HIERARCHY,
    ASSET_DOWNTIME,
    LOW_STOCK_ALERTS,
    PARTS_COST_TRACKING,//TODO
    CUSTOMER_VENDOR,
    FIELD_CONFIGURATION,
    VOICE_NOTES,
    ADVANCED_ANALYTICS,//TODO
    API_ACCESS,//TODO
    UNLIMITED_ASSETS,
    UNLIMITED_LOCATIONS,
    UNLIMITED_PARTS,
    UNLIMITED_PM_SCHEDULES,
    UNLIMITED_ACTIVE_WORK_ORDERS,
    UNLIMITED_CHECKLISTS,
    UNLIMITED_METERS,
    UNLIMITED_USERS
}
